# Generated by Django 3.1.1 on 2020-10-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_custumer',
            field=models.BooleanField(default=True),
        ),
    ]
