# Generated by Django 3.1.1 on 2020-10-09 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201009_1126'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
