# Generated by Django 3.1.1 on 2020-10-06 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20201006_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category',
            new_name='product',
        ),
    ]
