# Generated by Django 3.1.1 on 2020-10-06 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20201006_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='product',
            new_name='fname',
        ),
    ]
