# Generated by Django 3.1.1 on 2020-10-06 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20180821_2311'),
        ('restaurant', '0006_auto_20201006_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
